---
version: '3'
services:

    service:
        build: service/
        environment: 
            PORT: 8080
            LOG_LEVEL: "debug"
        ports:
            - "8115:8080"
        volumes:
            - ./service:/go/src/github.com/italolelis/epioca/service
        command: "CompileDaemon -build='go install ./cmd/epioca' -command=epioca"


    web:
        build: web/
        ports:
            - "8116:8080"
        volumes:
            - ./web:/server/http
    postgres:
        image: postgres:9.6
        ports:
            - '5432:5432'
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: epioca
            POSTGRES_PASSWORD: epioca
            POSTGRES_DB: epioca
